env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=SuOjLO9ODN9GIlWL5nVvOhUriC1mkAEo0

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
